apiVersion : apps/v1
kind: Deployment
metadata:
  name: "saracluster-787c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "saracluster-787c"
  template:
    metadata:
      labels:
        app: "saracluster-787c"
    spec:
      containers:
        - name: "saracluster-787c"
          image: "saracontainer.azurecr.io/saracluster"
          ports:
          - containerPort: 80