on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: saracontainer.azurecr.io
        username: ${{ secrets.acr_saracontainer_username }}
        password: ${{ secrets.acr_saracontainer_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t saracontainer.azurecr.io/saracluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push saracontainer.azurecr.io/saracluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_saracluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-demo | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-demo`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-demo
        container-registry-url: saracontainer.azurecr.io
        container-registry-username: ${{ secrets.acr_saracontainer_username }}
        container-registry-password: ${{ secrets.acr_saracontainer_password }}
        secret-name: saraclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-demo
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          saracontainer.azurecr.io/saracluster:${{ github.sha }}
        imagepullsecrets: |
          saraclusterdockerauth
